name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Disarankan menggunakan versi terbaru

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Disarankan menggunakan versi terbaru
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci # 'ci' lebih cepat dan direkomendasikan untuk CI/CD

      - name: Build Application
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Write Service Account to file
        run: echo "${{ secrets.GCP_SA_KEY }}" > ${{ github.workspace }}/gcp-key.json

      - name: Deploy to Firebase Hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-key.json
        run: |
          # Perintah deploy yang sudah diperbaiki, tanpa teks tambahan di akhir
          firebase deploy --only hosting --project "${{ secrets.FIREBASE_PROJECT_ID }}"
